kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-volume-claim
  namespace: mongodb
spec:
  storageClassName: mongodb-volume
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---