apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  namespace: mongodb
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-volume
  local:
    path: /home/lmsmaker/kube-mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lmsdev.shop
---