apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_ROOT_USERNAME: cm9vdAo=
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQK
  MONGO_USERNAME: dXNlcgo=
  MONGO_PASSWORD: cGFzc3dvcmQK
---