apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_ROOT_USERNAME: cm9vdA==
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ=
  MONGO_USERNAME: dXNlcg==
  MONGO_PASSWORD: cGFzc3dvcmQ=
---

