kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-volume
  namespace: mongodb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---

